title:        Developer
url:          http://developer.apievangelist.com

logo:         https://s3.amazonaws.com/kinlane-productions/api-evangelist/developer-api-evangelist.png
logo_width:   80
logo_bottom_padding: 10

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

categories_path : /categories.html
tags_path : /tags.html

org: api-evangelist
repo: master
resource: master
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI

# Masthead title
masthead_link: http://developer.apievangelist.com
masthead_font_size: 85
masthead_title: '{"Developer"}'

# Feature
feature_title: API Design Providers Guide
feature_link: http://apis.how/xzca4kr2wb
feature_image_source: https://s3.amazonaws.com/kinlane-productions/whitepapers/3scale/report-image-api-design.png
feature_image_width: 45

# Project
project_image: https://s3.amazonaws.com/kinlane-productions/bw-icons/bw-robots.jpeg
project_summary: This is the master portal where I access all of the APIs I depend on to run my world as Kin Lane. Visit the getting started page to kick things off, and if you have any questions let me know. These APIs are meant to run my own infrastructure, and are always in development, but I encourage others to poke around, and let me know their thoughts.

# Navigation
navigation:
  - label1: Home
    link1: /index.html
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 0
    padding: 0
    decorate: 0
  - label1: Getting Started
    link1: /getting-started/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Blog
    link1: /blog/
    size1: 80
    extend: 1
    label2: RSS
    link2: /blog.xml
    size2: 60
    padding: 5
    decorate: 0
  - label1: Support
    link1: /support/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Pricing
    link1: /pricing/
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 60
    padding: 0
    decorate: 0
  - label1: Return to API Evangelist
    link1: http://apievangelist.com
    size1: 80
    extend: 0
    label2:
    link2:
    size2: 10
    padding: 12
    decorate: 1

# Footer Navigation
footernavigation:
  - label: API 100K View
    link: http://apievangelist.com
  - label: News
    link: /news/
  - label: Partners
    link: http://apievangelist.com/partners/
  - label: APIs.json
    link: http://apisjson.org
  - label: About Kin Lane
    link: http://kinlane.com
  - label: Branding Guidelines
    link: http://apievangelist.com/branding-guidelines.html
  - label: Contact
    link: http://kinlane.com/contacts/

# sponsors
sponsors_margin_top: 15
sponsors_padding_top: 3
sponsors_json_url: https://s3.amazonaws.com/kinlane-productions/json/sponsors.json
