title:        API Evangelist
url:          http://developer.apievangelist.com
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

production_url : http://developer.apievangelist.com

BASE_PATH : http://developer.apievangelist.com

categories_path : /categories.html
tags_path : /tags.html

org: kinlane
repo: developer-api-evangelist
resource: developer-api-evangelist
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI
